language: go

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
go:
- "1.10"

go_import_path: github.com/container-mgmt/messaging-library

install:

# Install required Go tools:
- go get github.com/golang/dep/cmd/dep
- go get golang.org/x/lint/golint
- go get github.com/client9/misspell/cmd/misspell
- pip3 install pylint --user

# Install ActiveMQ Artemis and create an instance:
- wget --output-document artemis.tar.gz "https://www.apache.org/dyn/closer.cgi?filename=activemq/activemq-artemis/2.6.1/apache-artemis-2.6.1-bin.tar.gz&action=download"
- echo "b56d27107c6b362eb31a85d2a4720134b3142c5f2ed61d44a08eda57fc3764d6 artemis.tar.gz" | sha256sum --check
- mkdir --parents $HOME/artemis/home
- tar --strip-components=1 --directory=$HOME/artemis/home --extract --file=artemis.tar.gz
- $HOME/artemis/home/bin/artemis create --home=$HOME/artemis/home --host="localhost" --silent $HOME/artemis/instance
- $HOME/artemis/instance/bin/artemis-service start

script:
- python3 -m pylint build.py
- if [ $(gofmt -s -l ./pkg/ ./cmd/ | wc -l) -eq 0 ]; then true; else false; fi;
- make lint
- make build test
- make binaries
- misspell -error cmd/** pkg/** README.adoc
- make bench
