language: go

go:
- "1.10"

go_import_path: github.com/container-mgmt/messaging-library

install:
- go get github.com/golang/dep/cmd/dep
- go get golang.org/x/lint/golint

script:
- make build test lint
